### ISSUE TITLE
Quine support

### ISSUE THREAD

**Issue by ConorLPBoyle** [WICG/native-file-system#102]
Some single page applications such as [Tiddlywiki](https://tiddlywiki.com/) save their data by outputting a new HTML source file containing both the editor and the user's data. Maintaining such single-file wikis became much more cumbersome when the legacy file access APIs that browser saver extensions relied on were deprecated out of security concerns.

Am I correct in understanding that this API would allow seamless local autosave support for such quine applications after permission to save into the file is granted, or are there practical/security considerations that might prevent a local page (opened through file:///) from retaining a file handle to its own source file? And, would the file handle permission persist after a page reload into a newly modified version of itself?

**Comment by pwnall** [comment]
As far as I know, `file://` pages are technically not part of the Web, because they're not loaded from an HTTP server. So, support of this API on `file://` origins would be browser-dependent.

I don't think we want to support `file://` origins for this API in Chrome. In the long term, I'd like to have `file://` origins in Chrome not get access to any storage APIs.

**Comment by GeoMarkou** [comment]
I'm currently using this API in a ```file://``` context, and would be sad to see it go.

I converted a file management application from C# to React using the native file system API, and have had amazing success with it. Even with the relatively limited feature set in the current implementation.

It's really convenient being able to just open a .html file and start using the application. Having to set up a nginx web server or something similar would make the application a lot less portable. I feel like if this API's goal is to make websites feel more like desktop applications, then being able to share standalone .html files like .exe files is important.

**Comment by mkruisselbrink** [comment]
This is currently largely up to browsers, per the URL spec leaving the origin of a file URL open as "an exercise to the reader". I don't think there is anything for this spec to say in this area. If a browser makes the decision that file URLs aren't opaque origins, this will probably work, otherwise it won't work (as opaque origins can't be secure contexts in that case).
