### ISSUE TITLE
ChooseFileSystemEntriesType enumeration values don't match - Angular 8

### ISSUE THREAD

**Issue by Laurisylva** [WICG/native-file-system#106]
I'm working on an Angular's project on localhost, i simply tried to use the chooseFileSystemEntries fonction.
Without arguments, it works (openFile by default).
With arguments, it doesn't work and return an error. I tried obvious different values, even 'openFile' doesn't work.
I checked the documentation but i have no idea what i could write else..

[Documentation - 3.1. The chooseFileSystemEntries() method](https://wicg.github.io/native-file-system/#api-choosefilesystementries)

My basic function on Angular 8 :
```
async openDir() {
    this.opts = { "type" : "openDirectory" };
    this.handle = await (window as any).chooseFileSystemEntries(this.opts);
    console.log(this.handle);
}
```
Error in the browser console :
`TypeError: Failed to execute 'chooseFileSystemEntries' on 'Window': The provided value 'openDirectory' is not a valid enum value of type ChooseFileSystemEntriesType.`

Note : I use (window as any) for avoiding the error in the Angular CLI "error TS2339: Property ‘chooseFileSystemEntries' does not exist on type 'Window' "

Thank you for your help ! :)

**Comment by mkruisselbrink** [comment]
The spec changed to lower-case-dash-separated instead of camelCase, but that doesn't seem related to your issue, as the implementation still only supports the camelCase values as you are using here.

So with that said, I have no idea what would be going on here, afaict it shouldn't be possible to get the error you are getting. This does seem more like an implementation bug than a spec bug though, so could you perhaps re-port this issue on https://crbug.com/new, ideally with an actual (small) repro case we can try to run?

**Comment by Laurisylva** [comment]
I'm not English and i'm not sure how to use the Chromium Bugs website.. If someone knows how to do, thanks to report this bug haha
