### ISSUE TITLE
getEntries() iteration order in the face of changes?

### ISSUE THREAD

**Issue by foolip** [WICG/native-file-system#127]
https://wicg.github.io/native-file-system/#api-filesystemdirectoryhandle-getentries is a TODO for normative text, and one thing that seems important to define well is what happens if the entries change during iteration. It's probably a good idea to define the iteration order even for a static case to not depend on the underlying file system's order, but then entries added during iteration would have to either not show up at all, or show up at the end out-of-order.

This would affect https://github.com/WICG/native-file-system/issues/47 in the same way, cc @domenic @Ms2ger.

**Comment by mkruisselbrink** [comment]
If we want to define some kind of iteration order, we're more or less forced of iterating the entire directory before returning anything to javascript. If that's what we end up doing there really isn't any point in this being an async iterable, as there isn't any async going on once you're iterating... 

Having said that, I'm not sure if that would actually be a concern. A reason we came up with this API was because the existing `<input type=file webkitdirectory>` is notoriously slow/OOMs easily when selecting large directories. But that is for two reasons that don't apply here: First it recursively iterates the entire directory, while here we don't recurse. And secondly it also creates javascript objects for every file before returning anything to script. Here too, even with a sync iterable we'd only return one javascript object at a time.

So perhaps there is indeed not really a reason for something like getEntries to be an async iterable, and instead we could just have a sync iterable that returns entries in a well defined (sorted by name?) order...

If we do at some point would want to add convenience methods for things like recursive iteration that operation might need to return an async iterable, and defining a well-defined order for that would be much harder. But for the operations we have today perhaps we don't need to do anything special.

There is also some discussion on #56 and #57 where some people have expressed concerns about being able to cancel and backpressure directory iteration when iterating large directories, but we haven't actually measured the overhead, so not sure how much we're actually gaining by this being an async iterable.

**Comment by domenic** [comment]
Hmm. I'm not sure getting the order to be cross-platform the same is worth the loss in efficiency and generality here that async iterable provides. Maybe it's my Node.js background showing through here, but I was hoping this would directly delegate to the appropriate OS constructs, e.g. POSIX [readdir](https://pubs.opengroup.org/onlinepubs/9699919799/functions/readdir.html).

I wonder if concrete interop concerns could be helped by pointing to relevant OS-level documentation and specs. That would not guarantee the same iteration order across different OSes (or maybe even across different filesystems on the same OS), but it would prevent incompatibility between browsers operating on the same filesystem.

Alternately, you could pick one native behavior is, and specify that. Then platforms which don't match that would have to go through extra implementation hoops in order to match that, but at least one platform would be able to be implemented with maximum efficiency. Maybe multiple platforms have the same behavior, even.
