### ISSUE TITLE
Guarantees when racing creation and deletion?

### ISSUE THREAD

**Issue by foolip** [WICG/native-file-system#128]
[`FileSystemDirectoryHandle`](https://wicg.github.io/native-file-system/#api-filesystemdirectoryhandle) has methods for creating and deleting files and directories. When these async operations are raced in parallel, are there any guarantees about which will succeed/reject and the order?

I believe the most ergonomic would be if operations are done in the order they're requested.

**Comment by mkruisselbrink** [comment]
Not sure how useful giving guarantees is here... even if we make it well-defined how races between operations in the same event loop, there will still be races with other origins, races with other applications, etc.

Having said that, I do agree that what you're proposing would be the most ergonomic, but it would also be really hard to implement in chrome so I don't really want to give guarantees that we can't actually implement. If you're going to do multiple operations on the same files/directories without waiting for earlier operations to complete you're asking for trouble anyway, so while perhaps we could make (arguably) buggy code more predictable, I'm not sure it's worth the effort...

**Comment by mkruisselbrink** [comment]
Closing this, since I think the currently spec'ed behavior of not providing any guarantees is realistically the best we're going to do here. In practice for operations done through the same FileSystemDirectoryHandle instance operations are sort of ordered in chrome, but websites really shouldn't depend on any kind of ordering, and will always have to be able to deal with external modifications to the data anyway.
