### ISSUE TITLE
How do MIME types map to native file systems?

### ISSUE THREAD

**Issue by foolip** [WICG/native-file-system#133]
[`chooseFileSystemEntries()`](https://wicg.github.io/native-file-system/#dom-window-choosefilesystementries) supports MIME types and file extensions. The relevant part of the algorithm is still a TODO, but spelling out how one uses a MIME type to filter a list of candidate entries seems very important. It's probably one of:
- Mapping a MIME type to a set of extensions
- Sniffing the file content
- Some file system or OS-level feature?

Any mismatch here could leave a site broken and unusable in some browsers, so this seems to warrant a fair bit of detail.

**Comment by fallaciousreasoning** [comment]
In the [file handling explainer](https://github.com/WICG/file-handling/), we require users of the API to specify their own mappings (as we may need to be able to open mime types that the browser/OS doesn't currently know about).

[WebShareTarget](https://wicg.github.io/web-share-target/level-2/#sharetargetfiles-and-its-members) does something similar, in that it requires users to specify all mime types and extensions that can be shared to the app (however there is no mapping).

This might warrant some thought because it could result in different behavior across platforms as well as across browsers (for example, in file handling, Linux only supports associations with mime types, not with extensions).

**Comment by fallaciousreasoning** [comment]
@mgiuca, you might have more context on the WebShareTarget stuff.

**Comment by mgiuca** [comment]
To elaborate on what Jay said, in file handling we picked up on the problem of "what if the site specifies only extensions (making it broken on MIME systems) or only MIME types (making it broken on extension systems)?" The partial solution we came up with was to not ask the developer to give us a set of MIME types + extensions, but to give us a mapping of MIME types to extensions, like this:

```js
{
  "image/jpeg": [".jpg", ".jpeg"],
  "image/png": [".png"]
}
```

This isn't fool-proof (they could still give the wrong extensions or no extensions) but at least it encourages developers to think about the mapping between the two, and also lets them give us a mapping which we can then send to the OS (for example, on Linux, we can create an extension -> MIME map based on the data given by the developer, instead of having to rely on a hard-coded list).

Native file systems could do something similar, or we could try to share the same data so developers don't have to repeat themselves.
