### ISSUE TITLE
Should the API support encodings other than UTF-8?

### ISSUE THREAD

**Issue by tomayac** [WICG/native-file-system#166]
While UTF-8 per default is fine, there was [user feedback](https://twitter.com/Simmerl19/status/1244581654611492866) from someone who wanted to open data from a legacy system that other encodings would be useful occasionally. 

For comparison, for example [Node.js supports additional formats](https://github.com/nodejs/node/blob/b6459ec49048be8c5e52c30652ee00b63f11566b/lib/buffer.js#L597-L673) while defaulting to UTF-8.

**Comment by mkruisselbrink** [comment]
I'd be tempted to say this is more a question for the encoding spec rather than this spec... After all you can always just pipe through a EncoderStream to encode strings into bytes (assuming you don't need too much random access). EncoderStream also only supports UTF-8 though.

Not sure why EncoderStream only supports UTF-8, but I'd be hesitant to add other encodings here if the canonical web platform encoding API doesn't support them either...

**Comment by inexorabletash** [comment]
> Not sure why EncoderStream only supports UTF-8, but I'd be hesitant to add other encodings here if the canonical web platform encoding API doesn't support them either...

It was a matter of being conservative; we wanted to be able to consume legacy data (decode), but avoid producing it via the API (encode). That said, the platform obvious supports encoding to legacy encodings (form submissions/URLs) so we can revisit it in the API if there is demand.

**Comment by tomayac** [comment]
I'll get back to the initial requester and ask them if `TextEncoder` or `TextDecoder` would resolve their use case.

**Comment by mkruisselbrink** [comment]
Closing this, since as said I think this is more a request for the encoding spec. If/when that spec supports more encodings we might reconsider if we should have shortcuts in this API to support those encodings directly, but I don't see any reason we'd support more encodings than the encodings spec.
