### ISSUE TITLE
How to get "choosen file/folder system path"

### ISSUE THREAD

**Issue by gnusiva** [WICG/native-file-system#178]
I am developing an educational app, were i need to show the users of my site which folder does they choose to store the site generated files. 

in fileHandle object, i dont see any method which giving me the full system path to convey the user about the location. 

Or is there any security reason behind this feature? if so, please explain me.

**Comment by Anoesj** [comment]
In short, you can't.

#36 and #145 may answer your question. 

#156 might be a future solution to your problem.

Hope that helps!

**Comment by mkruisselbrink** [comment]
Indeed, what Anoesj says. We don't think users would understand it if when selecting a file the website would for example learn the username of whoever selected the file because the file just happened to be inside their home directory. So for that reason we have no plans to expose the full path to the web.

**Comment by aallaass** [comment]
https://m.facebook.com/profile.php:id=253D100084204593272

**Comment by aallaass** [comment]
https://m.facebook.com/profile.php:id=253D100084204593272`[https://m.facebook.com/profile.php:id=253D100084204593272](https://m.facebook.com/profile.php:id=253D100084204593272) `

**Comment by aallaass** [comment]
#260
