### ISSUE TITLE
Change type of accepted extensions from sequence to sequence or string?

### ISSUE THREAD

**Issue by mkruisselbrink** [WICG/native-file-system#197]
Currently https://wicg.github.io/native-file-system/#dictdef-filepickeraccepttype defines accept as `record<USVString, sequence<USVString>> accept;`. It might be nicer if that were changed to `record<USVString, sequence<USVString> or USVString> accept;` to not require wrapping a single extension in an array.

This would also be more consistent with examples in the file handling API explainer (https://github.com/WICG/file-handling/blob/master/explainer.md).

**Comment by mgiuca** [comment]
(Since you asked my opinion on #195)

I generally like APIs with "`sequence<Thing> or Thing`", if the common case will be to only pass one value. You have to consider the cost of forwards-compatibility (i.e. code written to work in the new version of the spec won't be compatible with old browsers), but this is still in origin trial, right, so should be safe to change?
