### ISSUE TITLE
Support for temporary files

### ISSUE THREAD

**Issue by kenchris** [WICG/native-file-system#20]
Do you intent on supporting temporary files, or should people use indexeddb for that instead?

**Comment by mkruisselbrink** [comment]
That almost sounds more like two unrelated questions... Issue #10 I think is about use cases people could otherwise use indexeddb for (i.e. storage sandboxed to the origin).

Even more temporary files (whatever "temporary" means in this case, files that go away when you close the tab perhaps? Or just when the last "reference" goes away) are sort of already a thing with regular File/Blob instances. I guess a question then would be if we should support some way of using FileWriter (or WritableStreams) to create new File/Blob instances. Maybe we should allow the FileSystemFileHandle constructor to be used to create such a file that only lives as long as the handle is alive.

**Comment by mkruisselbrink** [comment]
Temporary files with the lifetime of other storage mechanisms like IndexedDB is sufficiently addressed with the sandboxed file system support, I think. Even more temporary files/directories seems like a potentially interesting addition, although without use cases it would be hard to evaluate what the best shape of such an API would be. So closing this for now, until somebody comes up with compelling use cases.
