### ISSUE TITLE
getOriginPrivateDirectory is not a name that's friendly to partitioning

### ISSUE THREAD

**Issue by annevk** [WICG/native-file-system#211]
It assumes that the storage key will forever be an origin, which is less and less the case.

**Comment by inexorabletash** [comment]
Good point. Any name suggestions?

**Comment by annevk** [comment]
`getStorageDirectory()` or some such? Or `navigator.storage.getDirectory()`?

**Comment by mkruisselbrink** [comment]
I'm leaning towards either `navigator.storage.getDirectory()`, or moving the entire API surface to a FileSystem namespace (as suggested in #210), and thus ending up with `FileSystem.getPrivateDirectory()`. 
(i.e. either https://github.com/WICG/native-file-system/commit/6192c45405714f407bbca14f8537039403bf7dbb or https://github.com/WICG/native-file-system/commit/345af0acc7084a27213bbf78aa4d11882c124ee4)

navigator.storage seems a bit weird, since none of the other storage APIs are exposed via navigator, but that's probably okay. After all what existing APIs do via a singleton on the global seems to be explicitly against TAG guidance for new APIs.
