### ISSUE TITLE
API Usability Improvements

### ISSUE THREAD

**Issue by DanielHerr** [WICG/native-file-system#22]
I know the api shape is not final, but here are my suggestions for the current state:

1. There should be a single choose method under a Filesystem global instead of a method for each type. The choose method should be able to handle selecting multiple folders and files. It could throw an error if the platform cannot provide the required selector, and/or provide a method to determine the selection capabilities of the platform. I am not aware of any platform currently supporting combined selectors, but the file manager on Chrome OS does allow selecting a variety of files and folders and then opening them together with a Chrome App file handler. Example:
```
try {
 for await(let reference of FileSystem.choose({ file: true, folder: true, multiple: true, writable: true, type: "open" || "create", default: "Downloads" || "filename.txt", accepts: [{ types: [ "text" ], extensions: [ "json" ] }] })) {
  console.log(reference)
 }
} catch(error) {
 console.error(error)
}
```

2. Instead of using the FileReader api, file references should be similar to Response objects given by the fetch api. These methods use streams or promises to return the contents. Example:
```
try {
 let contents = await(file_reference.text() || file_reference.json() || file_reference.blob() || file_reference.arrayBuffer())
 let readable_steam = file_reference.stream()
 console.log(contents, readable_stream)
} catch(error)
 console.error(error)
}
```

3. Instead of using the FileWriter api, a write method should be directly on the file references. write() could support other types of data in addition to blobs and streams, and it can accept the position to begin writing as the optional second parameter. Example:
```
try {
 await file_reference.write("string" || new Blob || new ArrayBuffer || new WritableSteam, 1024)
} catch(error) {
 console.log(error)
}
```

4. It should be easy to read only files or subfolders from a parent folder, and have a recursive option to return the contents of subfolders. Example:
```
try {
 for await(let file_reference of folder_reference.read({ files: true, folders: false, recursive: true })) {
  console.log(file_reference)
 }
} catch(error) {
 console.error(error)
}
```

5. It should be possible to open or create a child multiple levels deep of a folder. Example:
```
try {
 let file_reference = await folder_reference.createFile("folder/subfolder/filename.txt")
 let subfolder_reference = await folder_reference.getFolder("topfolder/middlefolder/bottomfolder")
} catch(error) {
 console.error(error)
}
```

**Comment by inexorabletash** [comment]
re: #5 - using relative paths is present in the [old API](https://wicg.github.io/entries-api/) and I agree it should be supported for directory handle operations.

It does raise the question of whether rooted paths (e.g. `/foo`) should be supported. Probably?

**Comment by inexorabletash** [comment]
re: point 1 - can you describe your use case for allowing selection of both files and folders?

That'll help evaluate API shape discussions.

**Comment by mkruisselbrink** [comment]
Point 1 I believe is tracked/discussed in #25 (although there we're currently leaning to the opposite of what point 1 suggests here).

Point 2 I think is largely fixed by the addition of text/arrayBuffer/stream methods on Blob (although one could argue that it should be possible to skip the intermediate Blob/File object entirely; but that seems like a fairly minor improvement, so not sure it's worth the extra API surface.

Point 3 I disagree with. We gain a lot of options (like the current atomic writes) by making a file writer a separate object from the file reference. I don't think making the reference more statefull to somehow support having write methods directly on it would improve things at all.

Point 4 I split off into #173

Point 5 I'm not sure about... I kind of like that the API currently does not use actual paths as strings anywhere. But I do agree that it leads to somewhat awkward code if you do want to create nested directory trees etc... It does seem fairly straightforward to add whatever path support you want on top of what is provided as well, so I'm not sure the complexity of adding it is worth the effort. Feel free to file a separate issue explaining use cases/why being able to use paths would make things much easier though.
