### ISSUE TITLE
Add instructions for handling API calls from opaque origin

### ISSUE THREAD

**Issue by jarryd999** [WICG/native-file-system#77]
The spec should specify how to handle requests from an opaque origin, ie throwing a SecurityError DOMException.

**Comment by SteveBeckerMSFT** [comment]
I tried accessing storage APIs from a iframe with sandbox="allow-scripts".  Here are the results from Chrome and FireFox:

<input type=file> SUCCESS: can read the opened file.

drag&drop file SUCCESS: can read the dropped file.

localStorage FAIL: SecurityError: Failed to read the 'localStorage' property from 'Window': The document is sandboxed and lacks the 'allow-same-origin' flag.

indexedDB FAIL: SecurityError: Failed to execute 'open' on 'IDBFactory': access to the Indexed Database API is denied in this context.

cacheStorage FAIL: SecurityError: Failed to read the 'caches' property from 'Window': Cache storage is disabled because the context is sandboxed and lacks the 'allow-same-origin' flag.

Note that cacheStorage throws a SecurityError exception rather than rejecting the promise.

Proposal for Native File System API:

When accessed from an opaque origin, the native file system API should reject all promises with a SecurityError.  This is consistent with other storage types that have write operations.  If scenarios arise where this is too restrictive, we can always consider loosen this policy in the future.  

Thoughts?

**Comment by mkruisselbrink** [comment]
That sounds reasonable to me, thanks for doing that investigation!

**Comment by inexorabletash** [comment]
Asides, for context...

> Note that cacheStorage throws a SecurityError exception rather than rejecting the promise.

That's because the global `caches` is a property (`attribute` in IDL parlance) returning a value synchronously, so there's no promise to reject. Agreed that if the particular API (e.g. Native FS) has the appropriate entry point behind a promise, rejecting is the right thing to do.

Indexed DB is weird because some methods both throw on error (bad call) and return an IDBRequest that could return an error (async operation failed). With that model, calls from invalid contexts (opaque origins, third party cookies blocked, etc) were treated as the former type of error. 

So yeah, proposal LGTM2!
