### ISSUE TITLE
Consider renaming FileSystemDirectoryHandle's getFile() method to getFileHandle()

### ISSUE THREAD

**Issue by oyiptong** [WICG/native-file-system#98]
Given that JavaScript is a loosely typed language, the API naming is more important to reduce developer confusion.

* `FileSystemDirectoryHandle.getFile(name)` yields a `FileSystemFileHandle` object
* Calling the eponymous `FileSystemFileHandle.getFile()` method yields an object of type `File`

We should consider naming `FileSystemDirectoryHandle.getFile(name)` 
 with something close to the return type, e.g. `FileSystemDirectoryHandle.getFileHandle(name)`

**Comment by mkruisselbrink** [comment]
Thanks for filing this, yes, agreed that we need to do something here, just not sure what the best solution is. I.e. see http://wicg.github.io/native-file-system/#issue-6152e539 and http://wicg.github.io/native-file-system/#issue-a4e7d3b2.

If we do rename `getFile` to `getFileHandle` as you suggest we should also rename `getDirectory` to `getDirectoryHandle`. Or we could combine both into one `getChild` or `getEntry` method, and get rid of `getFile`/`getDirectory` entirely, instead relying on websites to check if the resulting type matches what they were expecting. Not sure what would be a more intuitive/easier to use API.

**Comment by foolip** [comment]
I came here to file the same issue, mostly because the resulting `await (await directoryHandle.getFile()).getFile() would be a strange thing to look at.

**Comment by Anoesj** [comment]
I think at first sight, combining `getDirectory` and `getFile` into `getEntry` makes sense, especially since it's impossible to have both a file and a directory with the same name. It might also fix the confusion around the `isDirectory` and `isFile` properties on `FileSystemHandle` (#116). But there's one problem: with `getEntry`, using the option `{ create: true }` would now require specifying what type of entry you want to create. Adding an option `type` and using it in combination with `create` looks a little confusing:
```javascript
// What does this do when there's a file called 'foo'?
const subdirHandle = await getEntry('foo', { type: 'directory', create: true })

// Reject if 'create: true' is used but 'type' is omitted? More scenarios = added complexity.
const subdirHandle = await getEntry('foo', { create: true })
```

#### Possible solutions:
1. Don't combine `getDirectory` and `getFile` into `getEntry`, but rename them to `getDirectoryHandle` and `getFileHandle` instead. This preserves the current directory/file creation behavior when using `getDirectoryHandle('foo', { create: true })` and `getFileHandle('foo', { create: true })`.
2. Combine `getDirectory` and `getFile` into `getEntry`, add a `type` option (`directory`/`file`) to filter results, but drop the `create` option and replace it with `createDirectory` and `createFile` methods (#153) or even a combined `createEntry` method, like so:
```javascript
// Get a file called 'foo' or create one if it doesn't exist yet
let file;
try {
  file = await getEntry('foo', { type: 'file' });
} catch {
  file = await createFile('foo');
  // or
  file = await createEntry('foo', { type: 'file' });
}
```

**Comment by mkruisselbrink** [comment]
I do kind of like the idea of merging `getFile` and `getDirectory` into one `getEntry` method (modulo bikeshedding on the name for that method), and then adding `createFile` and `createDirectory` methods. In that case `getEntry` would only return existing entries (and I think I wouldn't add a "type" option, instead leaving it up to callers to verify that they got the type they were expecting).

In that API the create methods could then have a flag to allow returning an existing file/directory or requiring creating a new one.

Although having said that, I'm not sure how often it would be useful to actually have such a unified `getEntry` method. Are there actually use cases where you don't care what type you're getting back?

So perhaps we should just keep the existing methods (modulo renaming to `getFileHandle` and `getDirectoryHandle`) and add the "always create" flag from #107 to them.
